server:
  port: 8882

# 增加数据库连接
spring:
  profiles:
    active: dev
#测试
test:
  hello: testcustoms12

#mybatis:
mapper-locations: classpath*:com/wiki/**/mapper/*Mapper.xml
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl